upstream ocr_service {
    least_conn;
    server ocr:3000;
}

server {
    listen 3000;
    client_max_body_size 36M;
    location / {
        proxy_pass http://ocr_service;
        proxy_http_version 1.1;
        proxy_set_header Connection "close";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
